### ISSUE TITLE
Write blog post post-HackNight1

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#10]
Nadiyah may be interested in another blog post after our Hack Night. Who wants to help with it?

**Comment by Aycrazy** [comment]
Too late for this? Being grouped with a blogpost for 2nd hack night?

**Comment by BarkleyBG** [comment]
Maybe we could write one blog post summarizing the first 3 Hack nights for Nadiyah? Perhaps we could distill the most important parts. 

Are we thinking of running our own blog? I don’t know if that’s where we want to spend our time, but we could do a monthly recap and retroactively write the first couple of posts.

**Comment by Aycrazy** [comment]
I agree. We seem to already have limited capacity. I don't think maintaining a blog is a priority. I wrote that first one because it was requested at the time.

**Comment by BarkleyBG** [comment]
This is stale. Plus now we've started a bigger conversation in #88 . so i'm closing this.
