### ISSUE TITLE
rearrange presentation of info on Meetup?

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#102]
There are a couple categories of information that need to be presented on Meetup (or similar)  for each hack night:

1. promotional information 
  - why people want to come
  - e.g., who is speaking
  - e.g., we can do better in the future to identify which projects will be in attendance (that's another issue for later tho)
2. logistics
  - e.g., where when and parking
3. rules
  - e.g., code of conduct, photography

I think our Meetup should stick to items in category 1., and then use comments/links to other places to describe 2. and 3. in detail. If we do this, then our event info will focus on promotional aspects - drawing people - and have less clutter in terms of the fine print (which is very important but may scare some people away)

**Comment by BarkleyBG** [comment]
Let's do this! Let's send a lot of this info to the digital program page.

**Comment by anthonyjesmok** [comment]
2 and 3 should be sent to Digital Program with a note in the Meetup about what the digital program containing and that it should be read.

**Comment by BarkleyBG** [comment]
I removed the verbatim info on code of conduct & photo release, and I instead just linked to our digital program for that information.

**Comment by BarkleyBG** [comment]
i'm closing this because I drafted February's in a way that meets this style https://www.meetup.com/Code-for-Milwaukee/events/267865857/
