### ISSUE TITLE
Food for HN 2020.01 - January 

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#103]
funding 
- [ ] determine funding
- [ ] secure funding ($ in account)

food
- [ ] determine where to get food
- [ ] determine what we want to order
- [ ] call ahead to ask if they can do that

drinks
- [ ] determine what soda/water to provide

execution
- [ ] place order
- [ ] pay for order
- [ ] arrange for pickup 
- [ ] also bring:
     - [ ] napkins
     - [ ] plates
     - [ ] utensils

(This issue can be copy-pasted again for future months)

**Comment by anthonyjesmok** [comment]
@BarkleyBG can you check the bag to see if we still have a good supply of napkins, plates, utensils, and cups? And also what beverages are still in stock?

@Aycrazy Have we received our funding from Layer One yet?

**Comment by BarkleyBG** [comment]
i can check the bag. I will let you know.

**Comment by BarkleyBG** [comment]
Beverages: water. 
Lots of napkins
70+ plates
30 spoons, 20 forks, a dozen sporks
1-2 dozen cups

**Comment by BarkleyBG** [comment]
I’m just bumping this from Dec to Jan because I’m too lazy to recreate it anew

**Comment by anthonyjesmok** [comment]
Alejandro ordered Damascus Gate and it was catered for January's hack night.
