### ISSUE TITLE
Write thank-yous to Layer One for hosting

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#108]
I think Brian can do this

**Comment by Aycrazy** [comment]
@BarkleyBG should see #111

**Comment by Aycrazy** [comment]
Even better #82

**Comment by anthonyjesmok** [comment]
Could we get a status on this @BarkleyBG ?

**Comment by BarkleyBG** [comment]
@anthonyjesmok I think @erinmagennis mailed them. I will confirm.

**Comment by BarkleyBG** [comment]
Erin indeed mailed them. All good!
