### ISSUE TITLE
Update website with our faces + contact info

### ISSUE THREAD

**Issue by erinmagennis** [codeformilwaukee/hack-night-planning#114]
Brian had a great idea of adding ourselves to the website. I think this will help make us seem more approachable and human. I think we can make this happen by December 19th. 

So it can be compiled in 1 place, please drop the following info in https://docs.google.com/document/d/1XfkzypvZOGkPLBb3x90m9_l917VLRp_dUThyeqvVp8w/edit
- Name
- Email
- LinkedIn, Github, or some other link (if you so desire)
- Image of you 

roll call 
- [x] erin
- [ ] mitch
- [x] romke
- [x] andrew
- [x] anthony
- [ ] alejandro
- [ ] brian

**Comment by Aycrazy** [comment]
Where should we drop this, here?

**Comment by BarkleyBG** [comment]
I just created a folder in the drive. Fill out this sheet and add a photo file to the drive. https://docs.google.com/document/d/1XfkzypvZOGkPLBb3x90m9_l917VLRp_dUThyeqvVp8w/edit

**Comment by BarkleyBG** [comment]
Case in point for this issue: we need to make it easier for people to contact us! https://github.com/codeformilwaukee/hack-night-digital-programs/issues/1

**Comment by Aycrazy** [comment]
Im not 100% sure that's the takeway. I think Zeno may have been playing around with github too

**Comment by Aycrazy** [comment]
Please do this!

**Comment by Aycrazy** [comment]
Should we add brief bios too?

**Comment by Aycrazy** [comment]
Let's just have linkedin links.  We can do Name, Face, Title, Link. @BarkleyBG and @romkedehaan  please share a face shot in this folder: https://drive.google.com/drive/folders/1LngXW5WWg5egGmKfBtHum2K89OpeK81S.  I can figure out the rest...

**Comment by romkedehaan** [comment]
https://rjefw55j9d-flywheel.netdna-ssl.com/wp-content/uploads/2017/07/Romke-de-Haan-Preferred.jpg

**Comment by Aycrazy** [comment]
Created very inelegant solution. That's what you get
