### ISSUE TITLE
HN7 Catering

### ISSUE THREAD

**Issue by esquivelan01** [codeformilwaukee/hack-night-planning#115]
-Meat: $11/lb Gyro/Chicken; $12/lb Beef; $.5C Pita Bread; 
-Veggie Friendly: $8 Spinach Pie - serves 1-2 people, $4 ½ dozen or $7 dozen falafel; 
-Pick up only; Couple days prior for ensured delivery 

Amounts we should order?

**Comment by Aycrazy** [comment]
Looks like we should be good for 25. We need to promote the event more
