### ISSUE TITLE
Promote Job Posting by Wisconsin Voices Partner - Empower

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#117]
We can put this in the pre-hack night 7 email

https://drive.google.com/file/d/0B7Hc7Ui-lOrwRG0yZklpXzhpSGNBSUhDZ0E2b2dWLVJFNmhr/view?usp=sharing

**Comment by BarkleyBG** [comment]
looks good to me, as long as we word it appropriately.

**Comment by anthonyjesmok** [comment]
@erinmagennis @BarkleyBG Did this go out in an email?

**Comment by erinmagennis** [comment]
Yes, it did.
