### ISSUE TITLE
as a non-partisan group, do we need to "no campaigning" and "dont handout flyers" at our events?

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#126]
Wondering what yall think

**Comment by erinmagennis** [comment]
Yes, I wasn't a fan of the guy that came last time, who dipped out after handing out his flyers. He was very "politiciany", portrayed a decent amount of lack of respect for me, and as shown through his actions has no real interest in being engaged in the CfM community. 

I think it is a different story if they are a committed member and want to share something of actual value, the speaker, or someone else we vet first. In which case we are probably going to share about it in the email/social media anyways.

**Comment by BarkleyBG** [comment]
In addition to the current code of conduct, what if we added something like this?

- No campaigning is allowed at CfM events. We are a non-partisan organization; please do not distribute flyers or other campaign materials.
- We do not allow most forms of recruiting on the behalf of for-profit organizations at our events, with the possible exceptions in the cases where the event is sponsored by, hosted by, or features a presentation from a for-profit organization. We are a non-profit organization focused on improving Milwaukee's public services via open source technologies, so we ask that no recruiting is done during CfM events. 
- If you have any questions about the above, please contact CfM. If in doubt of whether your actions may not be permissible, please refrain from those actions, or please get pre-approval from the CfM Core Team.
- If you have concerns about an attendee who you think may be running afoul of these rules, please bring this to the attention of the CfM Core Team members.

**Comment by anthonyjesmok** [comment]
Here is my proposal:

While Code for Milwaukee participates in a number of issues relating to civic politics and various levels of government, our organization aims to be non-partisan and does not endorse any political candidate for office. In addition, some of the venues we have used for events have restrictions on political activity that we must respect. Therefore, we have established these policies for any Code for Milwaukee event:

- We welcome politicians and political candidates to attend our events and participate in breakout groups, discussions, etc. in a non-political fashion. 
- No campaigning is allowed at CfM events. This includes distributing flyers or other campaign materials, collecting signatures, putting up signage on unauthorized areas, etc.
- We do not allow most forms of recruiting on the behalf of for-profit organizations at our events, with the possible exceptions in the cases where the event is sponsored by, hosted by, or features a presentation from a for-profit organization - as solely determined by the CfM Core Team. We are a non-profit organization focused on improving Milwaukee's public services via open source technologies, so we ask that no recruiting is done during CfM events.
- If you have any questions about the above, please contact CfM. If in doubt of whether your actions may not be permissible, please refrain from those actions, or please get pre-approval from the CfM Core Team.
- If you have concerns about an attendee who you think may be running afoul of these rules, please bring this to the attention of the CfM Core Team members at once so the matter may be resolved.
- Those found in violation of the policy will be given a single warning, asked to cease activity, and put any materials away. A second violation will result in the individual(s) being asked to leave, with non-compliance being escalated to building security or police.

**Comment by BarkleyBG** [comment]
i added a blurb under the code of conduct in the digital programs readme, so we have something for today. Let's review Mitch's edits soon.
