### ISSUE TITLE
Set up next 3-4 presentations (March-June)

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#128]
Prospects:
- John D. Johnson
- Gerardo Mares
- Someone from health department?
- Kat Tow - Accessibility
- Angelina Mosher-Salaazar - WUWUM reporter
- Erin -- Journal Sentinel Data Journalist
- Marquette students working with Mark Zachar
- Joe Peter-Angelo (?) be second appearance so maybe should get others before

**Comment by BarkleyBG** [comment]
I'm moving this to #19

**Comment by BarkleyBG** [comment]
can i close this?
