### ISSUE TITLE
Start a template for "how to introduce your project at a Hack Night"

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#14]
We received good feedback that some people would have been more interested & able to present their project at a Hack Night if they knew what they introduction should look like. Let's start a template for what an introduction should include:

- your name
- your project's main goal or purpose
- what stage is your project in
  - or, what you hope to work on or accomplish in short term
- any particular kind of help you want on this project
  - e.g., skills, programming languages, community partners
- anything that you can offer to others 

Shout out to Code + Brews for providing inspiration for this template

**Comment by BarkleyBG** [comment]
@Aycrazy Who do you think should be responsible for final approval of the template? Once approved, we can have @anthonyjesmok add it to the slide deck for July

**Comment by Aycrazy** [comment]
> @Aycrazy Who do you think should be responsible for final approval of the template? Once approved, we can have @anthonyjesmok add it to the slide deck for July

I think you and Erin are the authorities on this, but we can discuss it as a group (sans you) on Sunday

**Comment by BarkleyBG** [comment]
Added here: https://docs.google.com/presentation/d/1B2CdTh0DntF430I88xaBRXS-OIgkDq3Y90x6-tLllB8/edit#slide=id.g5dd10212c3_0_57
