### ISSUE TITLE
Create a slide for Sponsors/Partners for Hack Night & Other Presentations

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#17]
You know one of those slides with all the logos....

**Comment by BarkleyBG** [comment]
Depends on #37

**Comment by anthonyjesmok** [comment]
Let's revisit this for October strategic planning. If we need, or desire, anything similar for NDOCH, please let me know.

**Comment by BarkleyBG** [comment]
@Aycrazy I’m closing this
