### ISSUE TITLE
Orientation guide and slides

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#18]
This has been started

Further ideas

1. GitHub intro: (Migrated to #25 )
2. Perhaps the intro can use adding a project to the site as an example and it will actually become a pull request that's implemented

**Comment by Aycrazy** [comment]
https://discourse.codeforamerica.org/t/onboarding-best-practices/172

**Comment by BarkleyBG** [comment]
1. I explain git as a combination of file system + version control system. It looks like a file system, but its foundation is on version control and snapshots ("commits"). That, and a couple other key concepts seem to go a long way.

2. I think it could be easy to ask everyone to make a small pull request (add their name to a file, e.g.) on a dummy repo. This is a way to make it less scary & more human. A couple short exercises can work up to something "actual" or "implementable" while making small leaps

**Comment by BarkleyBG** [comment]
Erin and I will take this, & we are putting it in the New Member Orientation milestone

**Comment by BarkleyBG** [comment]
Here's a slide deck we're working on, with intent to use it for new member orientation: https://docs.google.com/presentation/d/1zhh6Pjm6opz5JMhDUb0Jad3gCHQ08OyJ6L2yZR30tHE/edit#slide=id.p

**Comment by BarkleyBG** [comment]
Update: the slide deck is _almost_ ready. The thing we have to do the most work on is #25 - creating an effective yet short intro to Github

**Comment by BarkleyBG** [comment]
@erinmagennis  and I will continue to polish the slide deck

**Comment by BarkleyBG** [comment]
closing because we have a first draft of the Orientation slides now
