### ISSUE TITLE
Order more name tags

### ISSUE THREAD

**Issue by romkedehaan** [codeformilwaukee/hack-night-planning#2]
Someone needs to own getting name tags

**Comment by Aycrazy** [comment]
How many do we have left?  Regardless we probably should get 50 more or something

**Comment by anthonyjesmok** [comment]
I ordered 200 more. They will be delivered to my house on Wednesday in time for Thursday.

**Comment by anthonyjesmok** [comment]
For when we need to reorder. https://www.amazon.com/gp/product/B07CR6ZBWH/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
