### ISSUE TITLE
Add photo waiver to Meetup RSVp

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#21]
Let's look at cfa discourse for how other brigades do this.  @romkedehaan @Aycrazy (I added Romke because he seems to know how to do this ;)

**Comment by anthonyjesmok** [comment]
The description for the September meetup has been updated. We had the waiver in previous meetup slides in the beginning, so I do not feel it is necessary for us to go back and update meetup details. The takedown information has been added. If all is satisfactory @BarkleyBG please close.
