### ISSUE TITLE
Who takes the CFM HN supplies box after July's HN?

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#22]
I have a small box of Hack Night supplies. I might not make the August 15th hack night. Who can take the box after July's hack night?

**Comment by anthonyjesmok** [comment]
We had spoken about keeping them at Romke's house or his No Studios office.

**Comment by erinmagennis** [comment]
Hi

**Comment by erinmagennis** [comment]
@anthonyjesmok but if Romke is gone for August, we should find a different solution for the time being. If the event is the 3rd week on August 15th I can take the box. If the hack night is moved to the 22nd someone else will have to take it because I won't be there.

**Comment by BarkleyBG** [comment]
Test. Hi @erinmagennis . Seems like it's easier to tag you now.
