### ISSUE TITLE
Create a form to capture skillset/interests of attendees/new members

### ISSUE THREAD

**Issue by erinmagennis** [codeformilwaukee/hack-night-planning#24]
Determine which format is best: 
- Short Google form
- Longer Google [follow-up form](https://docs.google.com/a/codeformilwaukee.org/forms/d/1LdB_ybRST2uPLkFK3B297vBmAtH9rc-sp3pz3hxXUVU/edit?usp=drive_web)
- submit a skill through github 
- conversations

**Comment by BarkleyBG** [comment]
How does this look @erinmagennis ? [CfM Orientation Poll](https://docs.google.com/forms/d/17BC3Vm0hjKlpzZhksQL0N0oGrJqo-Sl4PsA0rwICxjc/edit)

**Comment by erinmagennis** [comment]
decided on: Long Google Form
