### ISSUE TITLE
Confirm details for 20190727 Strategy meeting 

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#28]
Let’s meet on Saturday. We should attend both Hack & Tell as well as Milky Way. How can we attend both and also have a (brief?) strategy meeting amongst as many core team members as possible?

**Comment by erinmagennis** [comment]
I like Andrew's suggestion (I think it was Andrew's suggestion) to meet up at Hack and Tell at 2pm for a strategy session. 

Then those of us who want to go to Milky Way can and those at Hack & Tell will already be there and this meeting could be a brain break from whatever they were working on.

**Comment by BarkleyBG** [comment]
Milky Way runs 10-12 right? Should we consider moving the strategy session to 12:30 at Hack N Tell?

**Comment by erinmagennis** [comment]
12:30 is smarter. From what I understand, me, you/Brian, and Andrew will be at Milky Way. Then whenever we are done we can wander over to Hack & Tell where Mitch and Romke will be. 

However, Anthony is now busy so we won't be able to do the training video to deal with kiddos so another time will have to exist for that. @anthonyjesmok can those of us that will be there for August just show up early to hack night and watch it then?

**Comment by Aycrazy** [comment]
Oh yeah they (Hack & Milky) are in the same building!! So would it be cool if Katie came at 2 or do we want her to come earlier? 

All that said I may be a little late to Milky Way on account of my run group meeting that morning

**Comment by BarkleyBG** [comment]
I have some other things that have come up for Saturday. I'm working on scheduling. I hope to be able to make our Strategy meeting for an hour, but I dont think I'll attend Milky Way this time around. 

I'll be in touch about what time(s) work better for me, and I'll try to play a role in our strategy meeting & perhaps with Katie.

**Comment by Aycrazy** [comment]
All available will meet at the Hack N' Tell at 1pm, and hang around to talk with Katie Pritchard at 2pm on Saturday, July 27th
/polls Yes 'No'

**Comment by Aycrazy** [comment]
All available will meet at the Hack N’ Tell at 1pm, and hang around to talk with Katie Pritchard at 2pm on Saturday, July 27th
/poll “yes” “no”
