### ISSUE TITLE
Check if there’s a CFA Slack / github integration?

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#29]
It could be helpful to see if we can integrate github into our slack so we can open and close issues from slack 

https://github.com/integrations/slack/blob/master/README.md

**Comment by Aycrazy** [comment]
I think we can.

**Comment by anthonyjesmok** [comment]
I implemented a connection for the PFC and Hack Night planning repos. You can add more using the command `/github subscribe REPO_NAME`
