### ISSUE TITLE
More CfM Stickers

### ISSUE THREAD

**Issue by romkedehaan** [codeformilwaukee/hack-night-planning#3]
We need to order more stickers

**Comment by Aycrazy** [comment]
I'll order ones from the Code for Raleigh person that made the ones that Mitch brought back from the Summit

**Comment by BarkleyBG** [comment]
Good idea. We have a bunch in the box so we are set for July’s HN.

**Comment by Aycrazy** [comment]
I bought 200 and probably only have 40 left. Will need to do another order... But what I have, I can give to someone to bring on Aug 15th
