### ISSUE TITLE
Data Day Collaboration

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#33]
Data You Can Use (Dr. Katie Pritchard & Co) will be hosting the Data Day on Wednesday, October 23rd (all day)

We discussed the following ways of being involved:

Having an ask a Data Scientist/Civic Technologist Booth 
Key Questions:

- What is the ideal environment/setting/time for this to be offered at Data Day (at Data4BlackLives a couple of Data Scientists were available during the 1.5 hr lunch period)

- What types of questions can participants ask to get insight on what data science is, how and why it is used, and what the life of a data scientists/civic technologist looks like?  
   - Examples include:
            What is prediction?
            What is classification?
            Where is this used?
            What types of problems do you solve?

- Relevant & intriguing examples of where and how data science/ml is used

- Talking about job or role in industry

The following will be via a call for request response submission:

Data ignite [presentations](http://sixminutes.dlugan.com/ignite-presentations/)
Panels
Skills builder workshops

@BarkleyBG @erinmagennis @mitchellhenke @romkedehaan @anthonyjesmok

**Comment by BarkleyBG** [comment]
I like the Ask a Data Scientist booth. I could help find staffers for this. 

- Finding volunteers is probably easier after-work-hours. 
- Does DWCY have any info on what time Data Day will be running? Or any more information on the Data Day 2019?
