### ISSUE TITLE
Create blurb to drum up interest in NDOCH

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#38]
I want to drum up support for CfM, and NDOCH is a potentially a great event to do that. Can someone help to come up with a good 3-4 sentence blurb of why NDOCH is a great time to come to your first CfM event?

**Comment by BarkleyBG** [comment]
@anthonyjesmok also does words good

**Comment by Aycrazy** [comment]
pinging this again

**Comment by Aycrazy** [comment]
Any progress on this? @BarkleyBG @romkedehaan ?

**Comment by Aycrazy** [comment]
Here's a draft, loosely based on what @anthonyjesmok and I included in the NCDOH meetup page
https://docs.google.com/document/d/1Gyla6wNnphFcy7NJlTeNDHkulV82cZhIaQt3PVaUrg8/edit

**Comment by anthonyjesmok** [comment]
This looks good to me.

**Comment by BarkleyBG** [comment]
I haven’t read it. If y’all are happy then I trust you & we can ship it.
