### ISSUE TITLE
Signage

### ISSUE THREAD

**Issue by romkedehaan** [codeformilwaukee/hack-night-planning#4]
We need some signage for meetups

- [ ] sharpies
- [ ] tape
- [ ] Print out signs (@BarkleyBG ?)

**Comment by romkedehaan** [comment]
What should the signs say? I can design them. @anthonyjesmok @Aycrazy

**Comment by BarkleyBG** [comment]
IIRC, the signs are mostly for posting at the location (e.g., Lubar) on the day of the Hack Night to help orient people to the main hall. (We could also have signs for orienting people to the breakout rooms). If this is the case, then:
- "CFM Hack Night"
-  Logo 
- if desired: Room name 
- if desired: arrow or other directional (50/50 in either direction)

**Comment by Aycrazy** [comment]
Places:

- parking garage
- lobby
- entrances
- breakout rooms
   - M110 - Collaboration Space
   - S151 - main meeting space
   - S171 - Orientation
- Chalk signs? Joke?

**Comment by Aycrazy** [comment]
Whishlist: 
Giant Post-its

**Comment by romkedehaan** [comment]
[sign](https://drive.google.com/drive/u/3/folders/1xELm-cPPp80xAXv14g9Bih_tZTHoHIml)

**Comment by BarkleyBG** [comment]
I think I can print them on Thursday. Can anyone print them before then?

 - Brian 

Sent from my phone; please excuse any typos

**Comment by Aycrazy** [comment]
I can

**Comment by Aycrazy** [comment]
Done
