### ISSUE TITLE
NDOCH Marketing + Flyer

### ISSUE THREAD

**Issue by erinmagennis** [codeformilwaukee/hack-night-planning#46]
1. Implement a marketing plan: social media, articles/posts, invite other orgs/clubs 
2. Create flyer + post it around
3. Do we want to be on Bridge the City Podcast for this?

**Comment by Aycrazy** [comment]
Any movement on this?  
Being on Bridge the City would be great, would you have availability to set this up and be on the podcast, @erinmagennis?

**Comment by erinmagennis** [comment]
I won’t have time prior to NDOCH to be on the podcast (plus others would be better people to talk about NDOCH with greater accuracy). I could make an intro for someone else to do it.

**Comment by anthonyjesmok** [comment]
I can do it depending on days and times they're available. Perhaps myself
and Bryan?

**Comment by BarkleyBG** [comment]
I’m not familiar with Bridge the City. I’ll look into it

**Comment by Aycrazy** [comment]
Definitely a fan of the twofer! I have some important talking points that I need to translate to a better format than the stream of consciousness notes I shared yesterday that I'd like to be included in any earned media like this. So let's make sure we can huddle to discuss this before whoever goes "on air"

**Comment by Aycrazy** [comment]
RELEATED issue: https://github.com/codeformilwaukee/hack-night-planning/issues/38

**Comment by erinmagennis** [comment]
Just heard back from Bridge the city - they would love to partner with us on an event - they are scheduling out podcast times into oct/nov so no-go for short notice presence - they will promo ndoch though
