### ISSUE TITLE
Do we want permanent nametags/lanyards/shirts for Core Team and Committees?

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#48]
Would it be helpful if we had some way of visually designating Core Team or Committee members during hack nights? 

- I think if we had permanent (and color-coded?)  lanyards, then it would help us to be more approachable to new people at our hack nights.
- I also think that if we create a committee (say, project facilitation) then we could have lanyards for them so that they also are more approachable

There are questions about this:
- cost
- do we each take our lanyard home, or do we store them all in the magic box of goodies?
- etc

**Comment by anthonyjesmok** [comment]
I had found for PantherHacks some fluorescent vests for cheap. They are still on Amazon - $4.50 a piece. In the past, I have told people to identify core team members as those carrying radios, but the radios were often not used, left behind, and not visible - I will only be bringing them back for NDOCH where we will be spread out.

**Comment by erinmagennis** [comment]
I love the idea of lanyards! I also think they would find a nice home in the magic box.

**Comment by Aycrazy** [comment]
Pinging this. Otherwise we should let ppl know who we are at each hack night. Ppl don't automatically know who makes up the core team

**Comment by anthonyjesmok** [comment]
I like the vest idea still. Cost effective, transferable, and highly
visible.

**Comment by anthonyjesmok** [comment]
Team decided on light-up lanyards: amazon.com/gp/product/B076D4QLXN/ref=ox_sc_act_title_1?smid=A1DSFN25ZPZTQI&psc=1
