### ISSUE TITLE
Join Wisconsin STEM Fest list for Oct Hack-Night

### ISSUE THREAD

**Issue by erinmagennis** [codeformilwaukee/hack-night-planning#49]
Sign up to have our oct hack night (oct 17th) be part of this statewide stem fest on the 17/18th: 

https://wisconsinsciencefest.org/

**Comment by anthonyjesmok** [comment]
We cannot submit for this until we have a venue locked down.

**Comment by BarkleyBG** [comment]
@erinmagennis When is the deadline for us to get listed on the WI STEM Fest website?

**Comment by erinmagennis** [comment]
I just submitted it through the website's form.
