### ISSUE TITLE
Dry Erase Markers

### ISSUE THREAD

**Issue by romkedehaan** [codeformilwaukee/hack-night-planning#5]
We should get some dry erase markers for the night

**Comment by anthonyjesmok** [comment]
I ordered a pack of 40 to be delivered to me on Wednesday in time for Thursday

**Comment by BarkleyBG** [comment]
I have a handful in my bag right now, so we should have some backups.

@anthonyjesmok if you're expecting the 40 markers to come in on time tomorrow, we could close this issue now. Sound good?

**Comment by anthonyjesmok** [comment]
I'm closing this issue as we seem to be satisfied with the markers we have and they are now a part of the hack night box.
