### ISSUE TITLE
NCDOH Schedule

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#52]
RIght now we have Clean-Slate mentioned in two parts of the schedule.  Are we having Shanyeill as an opening keynote or a lunch time lunch and learn?  Once we figure that out, we can adjust the schedule and disperse the time for the other speakers in an even fashion.  

Another somewhat related update is that the #closeMSDF leadership retreat was changed to the following week, so Mark Rice of JustLeadership may be able to get involved as a presenter/moderator.

**Comment by anthonyjesmok** [comment]
Lunch and learn for Clean Slate.
