### ISSUE TITLE
Food for NDOCH 

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#56]
- breakfast?
  - yes
  - Colectivo? @mitchellhenke could you get the list of what Hack N Tells usually do?
  - Ruby's bagels?

- lunch?
  - not messy - need to keep the room clean

-  snax?
  - maybe this with lunch could be helpful?

- dinner?
  - maybe?

**Comment by mitchellhenke** [comment]
For hack & tell breakfast we usually get the bagel, bakery, muffin, and pastry platters, and a cambro of coffee from Colectivo

**Comment by anthonyjesmok** [comment]
@erinmagennis is talking to GMC on Wednesday, so @Dannycap if you could have any further information they will need for that that would be helpful.

**Comment by anthonyjesmok** [comment]
Food was delicious and plentiful. We need to remember a vegetarian issue for next time as we were unable to serve one individual due to muffins containing eggs.
