### ISSUE TITLE
Figure out how to get live microphone broadcasting!

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#58]
@Aycrazy 

- needs to be live
- UWM speaker cabinets are locked

**Comment by anthonyjesmok** [comment]
Architecture 170 is a lecture hall fitting approximately ~200 people.

**Comment by Aycrazy** [comment]
@BarkleyBG  any updates on friend's mics?

**Comment by BarkleyBG** [comment]
My friend’s mics will not be able to carry that room, I think. I can ask. How many people do you think we will get, maybe 50?

**Comment by anthonyjesmok** [comment]
I think 50 will be fine.

**Comment by BarkleyBG** [comment]
Possibility: An acoustic guitar amp that has an independent microphone amplifier channel, normally used for vocals. It may suffice in something up to a mid size lecture hall. It would not be powerful enough for an auditorium. Also, only one microphone input. So, you can't do an amplified QA session without passing the mic back and forth.

**Comment by BarkleyBG** [comment]
I can’t get the acoustic mike for Saturday. Sorry. We may have to go without.
