### ISSUE TITLE
Add a schedule of info to the meetup for NDOCH

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#60]
Also, blast out another:
- tweet
- insta
- slack chat on MKE
- slack chat on CFA

with the meetup link. Mention that we have updated the schedule. (@anthonyjesmok let me know if you have questions about details here)

**Comment by Aycrazy** [comment]
Location: UWM School of Architecture & Urban Planning - 2131 E Hartford Ave · Milwaukee, WI

Speakers:
- Lightening Talks:
    - Joe Peterangelo - [Wisconsin Policy Forum](https://wispolicyforum.org/staff-board/) -- find him in the page
    - Cameron Malakai
    - Nadiyah Johnson - (GE Healthcare/Jet Constellations)[https://www.bizjournals.com/bizwomen/news/profiles-strategies/2019/01/nadiyah-johnson-is-creating-an-urban-tech-hub-in.html?page=all]
    - Mark Rice (JustLeadership/Expo/#closeMSDF)[https://www.jsonline.com/videos/news/local/2019/08/20/once-incarcerated-he-now-works-restore-rights-others/1708952001/]
    - Sharmain Harris - (WIC Father Involvement Coordinator) [https://www.kenoshanews.com/news/20under40/sharmain-harris-finds-redemption-developing-better-fathers/article_0a0980a7-591d-5793-b65b-9a7d9715fa0c.html]

Idea: 10 min x 5 presenters with some transition time  = ~60 min
Panel: 40 min - Andrew to moderate (pre-set question + audience questions)
Total time: ~ 2 hours

As of now, I'll plan to moderate the discussion

We can consider starting the Shanyeill portion around 12:45/50 pm.
We'll wrap up her conversation around 1:45/50 then we'll get into hack stuff

**Comment by Aycrazy** [comment]
Check out https://www.rokkincat.com/hack-n-tell/ for the hacking portion schedule and adapt
