### ISSUE TITLE
Initial thanks to NDOCH attendees

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#72]
W/ info for how to give feedback and info on next hack night. This one can be really short and simple

**Comment by BarkleyBG** [comment]
Code for America sent out an email from our meetup (without us knowing) soliciting feedback on their form (which will be sent to us with results) and thanking people for attending. I can send a follow-up.

**Comment by Aycrazy** [comment]
Can you please include this link to Joe Peterangelo's presentation? https://drive.google.com/file/d/0B7Hc7Ui-lOrwRDk3bXpqejY3Mjh3SFFrSWhWX3FSbk5EY1Qw/view?usp=sharing

**Comment by Aycrazy** [comment]
React Traning info:  Code for Milwaukee members can use CodeForMKE for a free ticket:
https://www.eventbrite.com/e/building-your-first-react-app-tickets-73364488159

**Comment by anthonyjesmok** [comment]
This is done - thank you @erinmagennis for sending out the email!
