### ISSUE TITLE
NDOCH Feedback Forum

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#73]
Hey @anthonyjesmok. I looked at this a bit, and it seems it'd be difficult to draft questions together.  Since I am going to Brigade Congress and can provide some feedback there, do you think you can take care of this?

Take the quick 2-minute survey here: http://c4a.me/ndoch-survey
Share you photos and videos here: http://c4a.me/ndoch-folder

**Comment by anthonyjesmok** [comment]
Photos uploaded, survey complete!
