### ISSUE TITLE
Setup amazon smile charity?

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#78]
Small increments can go a big way to helping us

**Comment by Aycrazy** [comment]
Somehow would need to rig this up so that we get earmarked in smile donations to CFA

**Comment by BarkleyBG** [comment]
1. CfA is on amazon smile.
  - we may be able to earmark this for CfM.
2. CfM is not.

---
**Amazon smile rules**, https://org.amazon.com/ 
Get Started
How do I register and receive donations for my charitable organization?

Registering your organization is easy. In order to register and receive donations, you must be an official representative of an eligible organization, and then follow these easy steps:

- Search for your charitable organization by name or EIN number and then select the organization you represent. Be sure to confirm you are selecting the correct organization, as many charitable organizations have similar names.
- Create an organization administrator account and accept the AmazonSmile Participation Agreement on behalf of your organization.
- Verify your email address (we recommend that you use an email address that is associated with your charitable organization).
- Submit your organization’s bank account information.
- Upload a copy of a voided check or bank statement to verify your organization’s bank account information.

**Comment by BarkleyBG** [comment]
not possible.
The smile donation platform thing is only good for one EIN and there’s no way for to earmark it to a certain brigade
