### ISSUE TITLE
Create system to mail merge thank yous

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#80]
Because i dont remember all the things

**Comment by anthonyjesmok** [comment]
@erinmagennis Is there a way we could use MailChimp for this?

**Comment by erinmagennis** [comment]
There's a way to use MailChimp for almost anything we would need email related. It just depends on how much time we want to spend setting it up/is it worth that time. What exactly are we needing to do here?

**Comment by BarkleyBG** [comment]
Perhaps thank-yous can be physical now?

**Comment by Aycrazy** [comment]
Using a google plugin for this, as long as you have a draft email, you can blast emails to ppl in a spreadsheet
