### ISSUE TITLE
Create a presentation for Data Day Ignite

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#81]
Hi Andrew, 

We're happy that you expressed an interest in presenting at Data Day!  I want to check in with you on it to make sure you're still available and interested, and let you know about our practice sessions.  As a reminder, it's Tuesday, October 22nd at the Northwestern Mutual’s Cream City Labs, 733 N Van Buren St.  

The format for a 5 minute IGNITE is to present using a set of 20 slides, which auto advance during your presentation every 15 seconds.  If you like, you can watch past recordings of Data Day IGNITEs.

The timing can be tricky, so I'm setting up two practice sessions for our IGNITE speakers.  Please let me know if you are interested in attending either (or both!):
Tuesday, October 15th 8:30-9:30, and 
 Wednesday, October 16th, 3:30-4:30
I'm available if you have any questions or want any other help,

Carrie Koss Vallejo

**Comment by BarkleyBG** [comment]
This is different from #33 right?

**Comment by Aycrazy** [comment]
It's a subtask

**Comment by Aycrazy** [comment]
@mitchellhenke is gonna take this one!
