### ISSUE TITLE
Help Nadiyah to Staff the Tech for Good Event 

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#84]
I know she needs team "mentors"/helpers at least. @anthonyjesmok and @romkedehaan have been in touch with her about the event. I'll let them add more

--- 
event info
- link: https://www.eventbrite.com/e/the-milky-way-tech-for-good-pitch-out-tickets-73061319373

- Date And Time
Sat, November 16, 2019
6:00 PM – 8:00 PM CST

- Location:
88 Nine Studios
220 East Pittsburgh Avenue
Milwaukee, WI 53204

**Comment by anthonyjesmok** [comment]
I'm meeting with Nadiya and the planning group on Friday and will discuss what she needs from us to make the event a success.

**Comment by Aycrazy** [comment]
pls have some meeting notes for what comes out of the meeting on Friday/any questions you have for the group/ regarding CFA.

**Comment by BarkleyBG** [comment]
@anthonyjesmok were you able to make the meeting on Friday? Any updates?

**Comment by anthonyjesmok** [comment]
It's this Friday.

**Comment by anthonyjesmok** [comment]
Requests from Nadiyah
1. Use e-mail to send out link to application form to CfM membership in advance of deadline on October 10th. October 17th Hack Night in-person promotion will be too late.
2. Create Ad Hoc Meetup event for event to attract membership to the event and increase footprint.
3. Send logo for sponsorship list.

**Comment by Aycrazy** [comment]
Haha I've sent the logo to her at least 3 times
