### ISSUE TITLE
Find new Treasurer

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#85]
@Dannycap is riding off into the sunset on October 8th after putting in great work to set up the CfM finances. We will need to replace him.

Suggested next steps:
- [x] Draft up a notice of open Treasurer position
     - This should lay out the goals and responsibilities of position as it currently is
     - This should also mention that the applicant should be prepared to work with #79 if we go that route
     - Update: see the most recent position positing [here](https://docs.google.com/document/d/1T_1U4w9Z3vVVihTD4S7PYJOZFc86fqNVJEluQAUwkXM/edit)
     - When to close application? 
          - We want to introduce at HN5 oct 17th. 
          - Our next CT phone call is Weds 9th. Can we close on Oct 8th midnight?
- [ ] Put out e-flyer / ads / socials for the application
      - Put detailed info on our website, on a page we can link to
      - refer further Q's to the core team email address
- [ ] Review all applications
      - at Oct 9th phone call?
      - Do we want a second round of "interviews"?
- [ ] make a decision
- [ ] Inform all applicants
- [ ] I hope to announce the new Treasurer at HN5 on Thur Oct 17th

**Comment by Aycrazy** [comment]
I think this is solid. I'd like to add that we have a more detailed list of the socials we are posting in and who is responsible for posting it to each/replying to questions, reposting, having partners repost, etc

**Comment by BarkleyBG** [comment]
Let’s have all the advertisements say to “email XX for more information”

Who is XX? Andrew? 

We could also post more detailed info on our website and link there...

**Comment by anthonyjesmok** [comment]
I would say we post more information on our website and have applications go to the core-team email address for evaluation, just so we're in the loop in terms of all those applying and can review profiles as they come in.

**Comment by BarkleyBG** [comment]
Starting to work on the posting. We should say:

- looking for a treasurer. Unpaid / volunteer. CfM is nonprofit, and considering possibility of becoming 501c3 or other protected status.
- Estimated hours: Often 10-20 hours in a typical month, but can be as low as 1 hour if you help us to get our finances in order.
- responsbilities:
   - Current state: $ for HN food. Often help in ordering and picking up food. $ for other HN items like nametags. Keeping track of receipts and our bank account. Creating realtionships with potential partners. Finding disbursing $ for project infrastructre (AWS, etc) as in #69 
   - Should also plan to help us create more financial stability as in #79 

Dates:
  - app closes: Oct 9th?
  - Decision date: Oct 16th?
  -  start date: HN5 Oct 17th? 

Contact: Core Team email

Links: 
   - https://brigade.codeforamerica.org/resources/financial-administration

**Comment by BarkleyBG** [comment]
We can use wording similar to what we used for the original posting for Core Team back when we formed: https://docs.google.com/document/d/1GpmFHwV-WcjI6tcf0u0falYANGWCpiRm4vwJArOjkhI/edit

**Comment by Aycrazy** [comment]
How are we feeling about the state of the current description @BarkleyBG ?  When do you we want to start spreading the word about the opportunity?  What's the socials/general outreach plan @romkedehaan? Also, should we tell Max about the opp informally (soonish)?  Do we want to give him that advantage?

**Comment by Aycrazy** [comment]
Create a separate page for this opp and refer to it on the landing page

**Comment by BarkleyBG** [comment]
OH HAY @esquivelan01
