### ISSUE TITLE
Discern Involvement in upcoming Political Open Mic with BTC and Newaukee in November

### ISSUE THREAD

**Issue by Aycrazy** [codeformilwaukee/hack-night-planning#90]
Email from Rita DeMerit -- I think Mitch knows her? ;) --  from Newaukee

Hello again!

We met with our Political Open Mic team earlier this week to start sorting out details for the November event. Since it's falling during Startup Week, we're going around a tech theme focusing on privacy, policy, and public investment. Code for Milwaukee came up in our conversations, specifically around tech equity and civic engagement, and I was asked to reach out to see if you might be interested in participating in some way.

The date of the event is Wednesday, November 13th from 6-8PM, location TBD.

Let me know if you're available/interested and I'll connect you with the Bridge the City team to work out details.

**Comment by Aycrazy** [comment]
Getting more details from Kyle Hagge this afternoon.

**Comment by BarkleyBG** [comment]
Closing as past date?
