### ISSUE TITLE
Should we enumerate Hack Nights in 2020?

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#96]
Right now we informally refer to Hack Nights as "Hack night 6 - Nov". Would it be helpful to enumerate them by month, starting in the year 2020? E.g., "January Hack Night 20-1" and "Feb HN 20-2" or something?

**Comment by Aycrazy** [comment]
I like it

**Comment by erinmagennis** [comment]
That'll be helpful. I keep forgetting what number we are on. (Does anyone know?) I've given up counting at this point...

**Comment by BarkleyBG** [comment]
(@ erin ) October is supposedly our 5th total. January should be our 8th, or reindexing to 20-1.

**Comment by BarkleyBG** [comment]
Yes we will
