### ISSUE TITLE
Create page on website for sharing position postings

### ISSUE THREAD

**Issue by BarkleyBG** [codeformilwaukee/hack-night-planning#97]
I think this would work well as a subpage like `https://codeformilwaukee.org/join_us` or something. Ideally, we could have multiple postings at the same time, where each could be directly linked to the posting: `https://codeformilwaukee.org/join_us#treasurer` or `https://codeformilwaukee.org/join_us#websitemanager`. 

---
urgent:
I hope we could get a quick-and-dirty version up this weekend so we can post the Treasurer position #85 

--- 
long-term:
- at the top of this page, we should always have a 'posting' for _anybody_ to come join us at hack nights

**Comment by BarkleyBG** [comment]
If one of you web people could post a page with a Lorem Ipsum, I could put a PR in with the content for treasurer as soon as that's settled.

**Comment by Aycrazy** [comment]
Hidden position page: https://codeformilwaukee.org/join-us

**Comment by Aycrazy** [comment]
Not hidden. Up
