### ISSUE TITLE
$$$/Partnership/Project - from on the table mke due oct 31 

### ISSUE THREAD

**Issue by erinmagennis** [codeformilwaukee/hack-night-planning#98]
http://onthetablemke.org/ideas-to-action/?fbclid=IwAR01bwywOnQD2qF5bF7bOzxip5PBwJsbxPvuj1gM2BpGXwMsri_7qmuoz-k

I didn’t go to any of them, did any of you? Even if not we could offer out to any groups looking for partners.

**Comment by Aycrazy** [comment]
Let's discuss at our next meeting. Application deadline is October 31st

**Comment by Aycrazy** [comment]
Some draft responses to app questions: https://docs.google.com/document/d/1oFTdHRFDrRBmayFpfWu0UXarlNb47p_hU5MNy1FdoNo/edit

**Comment by BarkleyBG** [comment]
andrew submitted, so we will close this. If we hear back, we will open new issue with new action items
